version: 2

updates:
  - package-ecosystem: "composer"
    directory: /
    schedule:
      interval: "monthly"
    versioning-strategy: increase-if-necessary
    
  - directory: /
    open-pull-requests-limit: 5
    package-ecosystem: "github-actions"
    schedule:
      interval: daily
      timezone: "Europe/Berlin"
